server:
  port: 9096
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sa
    username: root
    password: mysql
security:
  user:
    password: password
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
